using System.Reflection;
using System.Runtime.InteropServices;
using System.Windows.Resources;

[assembly: AssemblyTitle("FSAP 2012")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyCompany("Rinse04")]
[assembly: AssemblyProduct("FSAP 2012")]
[assembly: AssemblyCopyright("Copyright © Rinse04")]
[assembly: AssemblyTrademark("")]
[assembly: ComVisible(false)]
[assembly: Guid("2ee575fa-84cf-412e-a534-61f148cc5e58")]
[assembly: AssemblyFileVersion("1.0.0.1")]
[assembly: AssemblyAssociatedContentFile("data/pcdf2009.dat")]
[assembly: AssemblyAssociatedContentFile("data/pcdf2012.dat")]
[assembly: AssemblyAssociatedContentFile("data/pcdf2012_test_400k.dat")]
[assembly: AssemblyAssociatedContentFile("data/pcdf2012_test_400r.dat")]
[assembly: AssemblyAssociatedContentFile("resources/calculation%20of%20basement%20floors%20and%20walls%20u-values.pdf")]
[assembly: AssemblyAssociatedContentFile("resources/draft%20epc.htm")]
[assembly: AssemblyAssociatedContentFile("resources/hqm.xsd")]
[assembly: AssemblyAssociatedContentFile("2012_icon.ico")]
[assembly: AssemblyAssociatedContentFile("data/externaldefinitions.xml")]
[assembly: AssemblyAssociatedContentFile("resources/1.jpg")]
[assembly: AssemblyAssociatedContentFile("resources/2.jpg")]
[assembly: AssemblyAssociatedContentFile("resources/3.jpg")]
[assembly: AssemblyAssociatedContentFile("resources/4.jpg")]
[assembly: AssemblyAssociatedContentFile("resources/5.jpg")]
[assembly: AssemblyAssociatedContentFile("resources/6.jpg")]
[assembly: AssemblyAssociatedContentFile("resources/eer_red.bmp")]
[assembly: AssemblyAssociatedContentFile("resources/eu.bmp")]
[assembly: AssemblyAssociatedContentFile("resources/flats.jpg")]
[assembly: AssemblyAssociatedContentFile("resources/logo_accreditation.jpg")]
[assembly: AssemblyAssociatedContentFile("resources/redsmall.png")]
[assembly: AssemblyAssociatedContentFile("resources/roominroof.jpg")]
[assembly: AssemblyAssociatedContentFile("resources/sap_red.bmp")]
[assembly: AssemblyAssociatedContentFile("sap.exe")]
[assembly: AssemblyAssociatedContentFile("sap2009.exe")]
[assembly: AssemblyAssociatedContentFile("stroma%20win-rdsap.ico")]
[assembly: AssemblyAssociatedContentFile("materials/mastermaterials.el")]
[assembly: AssemblyAssociatedContentFile("materials/mechanicalfasteners.mf")]
[assembly: AssemblyAssociatedContentFile("fonts/dejavusans_0.ttf")]
[assembly: AssemblyAssociatedContentFile("resources/appendix%20k.pdf")]
[assembly: AssemblyAssociatedContentFile("resources/updates.rtf")]
[assembly: AssemblyVersion("1.0.0.1")]
